"""建議用另一個venv, 不然pip pkg會大洗牌"""

# pip install fiftyone
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="validation",
    label_types=[
        "detections",  # default
        #  "segmentations"
    ],
    classes=[
        "person",
        "bicycle",
        "car",
        "motorcycle",
        # "airplane",
        "bus",
        # "train",
        "truck",
        # "boat",
        "traffic light",
        # "fire hydrant",
        # "stop sign",
        # "parking meter",
        # "bench",
        "bird",
        "cat",
        "dog",
        # "horse",
        # "sheep",
        # "cow",
        # "elephant",
        # "bear",
        # "zebra",
        # "giraffe",
        # "backpack",
        # "umbrella",
        # "handbag",
        # "tie",
        # "suitcase",
        # "frisbee",
        # "skis",
        # "snowboard",
        # "sports ball",
        # "kite",
        # "baseball bat",
        # "baseball glove",
        # "skateboard",
        # "surfboard",
        # "tennis racket",
        # "bottle",
        # "wine glass",
        # "cup",
        # "fork",
        # "knife",
        # "spoon",
        # "bowl",
        # "banana",
        # "apple",
        # "sandwich",
        # "orange",
        # "broccoli",
        # "carrot",
        # "hot dog",
        # "pizza",
        # "donut",
        # "cake",
        # "chair",
        # "couch",
        "potted plant",
        # "bed",
        # "dining table",
        # "toilet",
        # "tv",
        # "laptop",
        # "mouse",
        # "remote",
        # "keyboard",
        # "cell phone",
        # "microwave",
        # "oven",
        # "toaster",
        # "sink",
        # "refrigerator",
        # "book",
        # "clock",
        # "vase",
        # "scissors",
        # "teddy bear",
        # "hair drier",
        # "toothbrush"
    ],
    max_samples=50,
)
