# Preset labels, you press number to change the label
labels:
  1: person
  2: car
  3: dog
  4: cat
  5: bicycle
  6: motor
  7: bus
  8: truck
  9: train
  0: unknown

# default label name, draw bbox with this label
default_label: object

# Auto save interval in seconds. -1 means disabled.
auto_save_per_second: -1
